<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QA-Alex-PC" name="com.automation.main.VerifySortingOfCoursesInCopyWindowOfRegularRecordings" tests="2" failures="0" timestamp="15 Jan 2016 12:29:08 GMT" time="186.350" errors="1">
  <testcase name="VerifySortingOfCoursesInCopyWindow" time="184.320" classname="com.automation.main.VerifySortingOfCoursesInCopyWindowOfRegularRecordings">
    <error type="junit.framework.AssertionFailedError" message="timeout">
      <![CDATA[junit.framework.AssertionFailedError: timeout
	at junit.framework.Assert.fail(Assert.java:50)
	at com.automation.main.LoginHelperPage.loginCourses(LoginHelperPage.java:119)
	at com.automation.main.VerifySortingOfCoursesInCopyWindowOfRegularRecordings.VerifySortingOfCoursesInCopyWindow(VerifySortingOfCoursesInCopyWindowOfRegularRecordings.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </error>
  </testcase> <!-- VerifySortingOfCoursesInCopyWindow -->
  <testcase name="testME" time="2.030" classname="com.automation.main.VerifySortingOfCoursesInCopyWindowOfRegularRecordings"/>
</testsuite> <!-- com.automation.main.VerifySortingOfCoursesInCopyWindowOfRegularRecordings -->
